---
title: "Introducción_R"
author: "Fernanda Tenemaza"
date: "26/2/2022"
output: html_document
---
**Crear un indetificador de nombre "ciudad" y asigne como valor el nombre de alguna ciudad**

  ciudad = "Puyo" 
**Crear un identificador de nombre "pais_andes" y asigne como valor los nombres de los países por donde cruza la cordillera de Los Andes**

pais_andes = as.factor (c("Argentina", "Bolivia", "Chile", "Colombia", "Ecuador", "Perú", "Venezuela"))
**Crear un dataframe con 12 eventos (files) y 5 variables (columnas),Cada columna debe tener diferentes tipos de datos (entero, decimal, caracter, logico)**

MUJERES_QUE_HAN_VIVIDO_ALGÚN_TIPO_DE_VIOLENCIA_DE_GÉNERO = data.frame("Provincias" = c("Azuay", "Tungurahua", "Pichincha","Morona Santiago", "Imbabura", "Cotopaxi","Esmeraldas", "Guayas", "Loja", "Napo", "Pastaza", "Orellana"),
                  "Mujeres violentadas" = c("195.622","142.132", "714.348", "32.406", "95.718", "95.909", "103.126", "775.537", "99.803", "21.401", "19.105", "19.937"), 
                  "Mujeres no violentadas" = c("88.916", "58.648", "309.216", "12.203", "55.054", "55.902", "73.991", "594.574", "68.447", "11.358", "8.280", "20.409"),
                  "Total mujeres investigadas" = c("284.538", "200.780", "1.023.564", "44.609", "150.772", "151.811", "177.117", "1.370.111", "168.250", "32.759", "27.385", "40.346"),
                  "% de mujeres violentadas" = c("68,8%", "70,8%", "69,8%", "72,6%", "63,5%", "63,2%", "58,2%", "56,6%", "59,3%", "65,3%", "69,8%", "49,4%"))
                  
**Cargue el dataset "DNase" e identifique su estructura.**
data()
DNase
head(DNase,12)
str(DNase)

**Extraiga (subset)los datos que cumplan con las condiciones de:**
**1. "conc" (concentracion) entre 0.1 y 0.2**
**2. "Run" diferente a 2, "conc" mayor a 0.2 y "density" menor o igual a 1.0**
first_filter <- filter(DNase, conc < 0.2 & conc > 0.1)
second_filter <- filter(DNase, Run != 2 & conc > 0.2 & density <= 1)